spring:
  application:
    name: datart-server
  main:
    banner-mode: off
  profiles:
    include: config,registry
    active: default

logging:
  level:
    root: error
#    datart: error
#    datart.core.mappers: debug
#    datart.data.provider.jdbc: debug
#    org.springframework.web: error
#    org.springframework.security: error
#    org.springframework.security.oauth2: error
#  config: config/logback.xml

shiro:
  web:
    enabled: false

frontend:
  address: http://localhost:3000

datart:
  server:
    address: http://localhost:8080
    path-prefix: /api/v1

server:
  port: 8080
  address: 0.0.0.0

  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
